# 74 utilisateurs à importer

USERS = [
    {'nom': 'Brassinne', 'prenom': 'Laetitia', 'fonction': 'Biologiste', 'email': 'l.brassinne@cdle.be', 'role': 'biologiste'},
    {'nom': 'Cauchie', 'prenom': 'Mathieu', 'fonction': 'Biologiste', 'email': 'm.cauchie@cdle.be', 'role': 'biologiste'},
    {'nom': 'Hotton', 'prenom': 'Julie', 'fonction': 'Biologiste', 'email': 'j.hotton@cdle.be', 'role': 'biologiste'},
    {'nom': 'Jacobs', 'prenom': 'Julie', 'fonction': 'Biologiste', 'email': 'julie.jacobs@cdle.be', 'role': 'biologiste'},
    {'nom': 'Miller', 'prenom': 'Nathalie', 'fonction': 'Biologiste', 'email': 'n.miller@cdle.be', 'role': 'biologiste'},
    {'nom': 'Vanneste', 'prenom': 'Franck', 'fonction': 'Biologiste', 'email': 'f.vanneste@cdle.be', 'role': 'biologiste'},
    {'nom': 'Mairesse', 'prenom': 'Antoine', 'fonction': 'Biologiste', 'email': 'a.mairesse@cdle.be', 'role': 'biologiste'},
    {'nom': 'Ngougni Pokem', 'prenom': 'Perrin', 'fonction': 'Assistant Biologiste', 'email': 'p.ngougnipokem@europehospitals.be', 'role': 'biologiste'},
    {'nom': 'Huysman', 'prenom': 'Carine', 'fonction': 'Coordinatrice qualité', 'email': 'c.huysman@cdle.be', 'role': 'qualiticien'},
    {'nom': 'Derycke', 'prenom': 'Hélène', 'fonction': 'Aide-laborantin', 'email': 'derycke.ln@gmail.com', 'role': 'technicien'},
    {'nom': 'Ronsmans', 'prenom': 'Kelcey', 'fonction': 'Aide-laborantin', 'email': 'k.ronsmans@cdle.be', 'role': 'technicien'},
    {'nom': 'Daugimont', 'prenom': 'Emmanuel', 'fonction': 'Coordinateur Labo', 'email': 'mdaugimont@gmail.com', 'role': 'responsable_technique'},
    {'nom': 'Boite', 'prenom': 'Gilles', 'fonction': 'Employé', 'email': 'gilles066@hotmail.com', 'role': 'technicien'},
    {'nom': 'Debusschere', 'prenom': 'Marie', 'fonction': 'Aide-laborantin', 'email': 'm.debusschere@cdle.be', 'role': 'technicien'},
    {'nom': 'Dewals', 'prenom': 'Véronique', 'fonction': 'Aide-laborantin', 'email': 'v.dewals@cdle.be', 'role': 'technicien'},
    {'nom': 'Haroun', 'prenom': 'Amina', 'fonction': 'Aide-laborantin', 'email': 'a.haroun@cdle.be', 'role': 'technicien'},
    {'nom': 'Jeegers', 'prenom': 'Déborah', 'fonction': 'Aide-laborantin', 'email': 'djeegers@gmail.com', 'role': 'technicien'},
    {'nom': 'Magnus', 'prenom': 'Karine', 'fonction': 'Secrétariat', 'email': 'k.magnus@cdle.be', 'role': 'technicien'},
    {'nom': 'Ngabena', 'prenom': 'Estelle', 'fonction': 'Aide-laborantin', 'email': 'ngabena@yahoo.fr', 'role': 'technicien'},
    {'nom': 'Riestra', 'prenom': 'Maïté', 'fonction': 'Aide-laborantin', 'email': 'm.riestra@cdle.be', 'role': 'technicien'},
    {'nom': 'Süssmilch', 'prenom': 'Jennifer', 'fonction': 'Aide-laborantin', 'email': 'jennifersussmilch@outlook.com', 'role': 'technicien'},
    {'nom': 'Van De Woestijne', 'prenom': 'Véronique', 'fonction': 'Aide-laborantin', 'email': 'v.vandewoestijn@cdle.be', 'role': 'technicien'},
    {'nom': 'Vercouter', 'prenom': 'Nathalie', 'fonction': 'Secrétariat', 'email': 'n.vercouter@cdle.be', 'role': 'technicien'},
    {'nom': 'Barbery', 'prenom': 'Adrienne', 'fonction': 'Préleveur', 'email': 'adriennebarbery01@gmail.com', 'role': 'technicien'},
    {'nom': 'Binda', 'prenom': 'Angèle', 'fonction': 'Préleveur', 'email': 'a.binda@cdle.be', 'role': 'technicien'},
    {'nom': 'Bitugangando', 'prenom': 'Franck', 'fonction': 'Préleveur', 'email': 'bifranck@outlook.com', 'role': 'technicien'},
    {'nom': 'Bouche', 'prenom': 'Isabelle', 'fonction': 'Préleveur', 'email': 'ibouche@yahoo.com', 'role': 'technicien'},
    {'nom': 'El Hamli', 'prenom': 'Amal', 'fonction': 'Préleveur', 'email': 'amal.el.hamli@cdle.be', 'role': 'technicien'},
    {'nom': 'Eslama', 'prenom': 'Nasira', 'fonction': 'Préleveur', 'email': 'n.eslama@cdle.be', 'role': 'technicien'},
    {'nom': 'Fayali', 'prenom': 'Iman', 'fonction': 'Préleveur', 'email': 'i.fayali@europehospitals.be', 'role': 'technicien'},
    {'nom': 'Kockx', 'prenom': 'Véronique', 'fonction': 'Préleveur (BVMC)', 'email': 'v.kockx@cdle.be', 'role': 'technicien'},
    {'nom': 'Nagoda-Nicklewicz', 'prenom': 'Eva', 'fonction': 'Préleveur', 'email': 'e.nagodaniklewicz@europehospitals.be', 'role': 'technicien'},
    {'nom': 'Roscail', 'prenom': 'Béatrice', 'fonction': 'Préleveur', 'email': 'b.roscail@europehospitals.be', 'role': 'technicien'},
    {'nom': 'Abdoulaye', 'prenom': 'Adama', 'fonction': 'TLM', 'email': 'manilleab@netcourrier.be', 'role': 'technicien'},
    {'nom': 'Abrak', 'prenom': 'Iman', 'fonction': 'TLM', 'email': 'iman.abrak@hotmail.com', 'role': 'technicien'},
    {'nom': 'Atsakena', 'prenom': 'Benjamin', 'fonction': 'TLM (nuit)', 'email': 'batsakena@gmail.com', 'role': 'technicien'},
    {'nom': 'Belleville', 'prenom': 'Bruno', 'fonction': 'TLM', 'email': 'bruno.belleville@gmail.com', 'role': 'technicien'},
    {'nom': 'Benabdelkrime', 'prenom': 'Nouh', 'fonction': 'TLM', 'email': 'nouh.ben@outlook.be', 'role': 'technicien'},
    {'nom': 'Bentatou', 'prenom': 'Zahra', 'fonction': 'TLM', 'email': 'bentatou_21@msn.com', 'role': 'technicien'},
    {'nom': 'Blauwaert', 'prenom': 'Nadège', 'fonction': 'TLM', 'email': 'n.blauwaert@cdle.be', 'role': 'technicien'},
    {'nom': 'Canas Torres', 'prenom': 'Dorian', 'fonction': 'TLM', 'email': 'doriancanastorres@gmail.com', 'role': 'technicien'},
    {'nom': 'Citti', 'prenom': 'Alessia', 'fonction': 'TLM', 'email': 'alessia.citti@hotmail.fr', 'role': 'technicien'},
    {'nom': 'Dahhou', 'prenom': 'Ghizlane', 'fonction': 'TLM', 'email': 'gdahhou24@gmail.com', 'role': 'technicien'},
    {'nom': 'Damblon', 'prenom': 'Simon', 'fonction': 'TLM', 'email': 'simondamblon@gmail.com', 'role': 'technicien'},
    {'nom': 'Darricades', 'prenom': 'Morgane', 'fonction': 'TLM', 'email': 'darricadesmorgane@yahoo.fr', 'role': 'technicien'},
    {'nom': 'De Sousa Marques', 'prenom': 'Sofia', 'fonction': 'TLM', 'email': 's.desousamarques@europehospitals.be', 'role': 'technicien'},
    {'nom': 'Demaret', 'prenom': 'Benoit', 'fonction': 'TLM (nuit)', 'email': 'bdemaret@skynet.be', 'role': 'technicien'},
    {'nom': 'Diaz de la Concha', 'prenom': 'Ana Belen', 'fonction': 'TLM', 'email': 'a.diaz@cdle.be', 'role': 'technicien'},
    {'nom': 'El Achab', 'prenom': 'Ikram', 'fonction': 'TLM', 'email': 'ikramelachab@hotmail.com', 'role': 'technicien'},
    {'nom': 'El Houdifi', 'prenom': 'Mounate', 'fonction': 'TLM', 'email': 'm.elhoudifi@cdle.be', 'role': 'technicien'},
    {'nom': 'Giambra', 'prenom': 'Elisa', 'fonction': 'TLM', 'email': 'elisa.giambra@icloud.com', 'role': 'technicien'},
    {'nom': 'Goutier', 'prenom': 'Sylvianne', 'fonction': 'TLM', 'email': 's.goutier@cdle.be', 'role': 'technicien'},
    {'nom': 'Guidotti-Peña', 'prenom': 'Isolde', 'fonction': 'TLM', 'email': 'isoldeguidotti66@gmail.com', 'role': 'technicien'},
    {'nom': 'Gündes', 'prenom': 'Armen', 'fonction': 'TLM (nuit)', 'email': 'armengundes@hotmail.com', 'role': 'technicien'},
    {'nom': 'Hernandez', 'prenom': 'Pauline', 'fonction': 'TLM', 'email': 'h.pauline0702@gmail.com', 'role': 'technicien'},
    {'nom': 'Jamaoui', 'prenom': 'Siham', 'fonction': 'TLM', 'email': 'jsiham@hotmail.com', 'role': 'technicien'},
    {'nom': 'Joseph', 'prenom': 'Nicolas', 'fonction': 'TLM', 'email': 'n.joseph@cdle.be', 'role': 'technicien'},
    {'nom': 'Kayisire', 'prenom': 'Céline', 'fonction': 'TLM', 'email': 'c.kayisire@cdle.be', 'role': 'technicien'},
    {'nom': 'Mahfad', 'prenom': 'Amina', 'fonction': 'TLM (nuit)', 'email': 'amina.mahfad@gmail.com', 'role': 'technicien'},
    {'nom': 'Maton', 'prenom': 'Agnès', 'fonction': 'TLM', 'email': 'agnes.maton@hotmail.com', 'role': 'technicien'},
    {'nom': 'Musoni', 'prenom': 'Lambert', 'fonction': 'TLM (nuit)', 'email': 'musonil@yahoo.fr', 'role': 'technicien'},
    {'nom': 'Muyldermans', 'prenom': 'Axel', 'fonction': 'TLM', 'email': 'axelmuyldermans@hotmail.com', 'role': 'technicien'},
    {'nom': 'Nae', 'prenom': 'Luminita', 'fonction': 'TLM (nuit)', 'email': 'nae.luminita@gmail.com', 'role': 'technicien'},
    {'nom': 'Natis', 'prenom': 'Valérie', 'fonction': 'TLM', 'email': 'natis_valerie@hotmail.com', 'role': 'technicien'},
    {'nom': 'Paquet', 'prenom': 'Florence', 'fonction': 'TLM', 'email': 'f.paquet@cdle.be', 'role': 'technicien'},
    {'nom': 'Senna', 'prenom': 'Tabata', 'fonction': 'TLM', 'email': 't.sennadagraalopes@europehospitals.be', 'role': 'technicien'},
    {'nom': 'Serroukh', 'prenom': 'Lamia', 'fonction': 'TLM', 'email': 'l.serroukh@cdle.be', 'role': 'technicien'},
    {'nom': 'Stuckmann', 'prenom': 'Charlotte', 'fonction': 'TLM', 'email': 'c.stuckmann@cdle.be', 'role': 'technicien'},
    {'nom': 'Swerts', 'prenom': 'Joël', 'fonction': 'TLM', 'email': 'j.swerts@cdle.be', 'role': 'technicien'},
    {'nom': 'Vanleemputten', 'prenom': 'Justine', 'fonction': 'TLM', 'email': 'j.vanleemputten@hotmail.fr', 'role': 'technicien'},
    {'nom': 'Verwerft', 'prenom': 'Edouard', 'fonction': 'TLM', 'email': 'ed.verwerft@hotmail.com', 'role': 'technicien'},
    {'nom': 'Visschers', 'prenom': 'Lucie', 'fonction': 'TLM', 'email': 'l.visschers@cdle.be', 'role': 'technicien'},
    {'nom': 'Zaaboul', 'prenom': 'Basma', 'fonction': 'TLM', 'email': 'basma.bo.zz@gmail.com', 'role': 'technicien'},
    {'nom': 'Zubani', 'prenom': 'Yves', 'fonction': 'TLM', 'email': 'yveszubani@voo.be', 'role': 'technicien'},
]
